SERVICE_CODE_KEY = "ServiceCode"
ORGANIZATION_ID_KEY = "OrganizationID"
CONTENT_KEY = "Content"
EVENT_CODE_KEY = "EventCode"


SUCCESS_KEYWORD = "Success"
FAILED_KEYWORD = "Failed"
STATUS_KEYWORD = "Status"
